name:                kiss
version:             0.1.0.0
github:              "ch3rn0v/kiss"
license:             BSD3
author:              "Ilya Chernov"
maintainer:          "ilya.v.chernov@gmail.com"
copyright:           "2020 Ilya Chernov"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Calculates arity and statement count for all the functions in a given project
# category:            Parser

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ch3rn0v/kiss#readme>

dependencies:
  - base >= 4.7 && < 5
  - directory
  - unordered-containers >= 0.2.10.0
  - containers
  - path
  - path-io
  - uniplate
  - text
  - lens >= 4.17.1
  - aeson
  - lens-aeson
  - extra

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  kiss-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kiss

tests:
  kiss-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kiss
